version: "3.8"
services:
  ts:
    image: typesense/typesense:0.23.1
    ports:
      - "${REACT_APP_TYPE_PORT}:8108"
    volumes:
      - "ts_data:/data"
    environment:
      TYPESENSE_API_KEY: "${REACT_APP_TYPE_API_KEY}"
      TYPESENSE_DATA_DIR: "/data"

volumes:
  ts_data:
